### ISSUE TITLE
Wen game?

### ISSUE THREAD

**Issue by gvanderest** [Mud-xyz/evermore-bugs#1]
There must be a bug, because the game is not yet launched.

**Comment by asyouw1sh** [comment]
ok I need GAME TO GO UP. like VERY SOON. I cant take this anymore. every day I am checking game and it is not up. every day, check game, game not up. I cant take this anymore, I have over invested, by a lot. it is what it is. but I need the game to GO UP ALREADY. can devs DO SOMETHING??

**Comment by gvanderest** [comment]
Harsh, but fair.
