### ISSUE TITLE
Cleave and Hack command broken 

### ISSUE THREAD

**Issue by Dzvin** [Mud-xyz/evermore-bugs#17]
Normally when using arcade mode I press Hack and Cleave and they work immediately, after an update released around 8 PM EST. 

![hack cleave borkn](https://user-images.githubusercontent.com/96559089/147184658-a398b965-32a0-45ca-a20e-e71ddf8d8472.PNG)

**Comment by ratacat** [comment]
Should be all fixed! Thanks
