### ISSUE TITLE
Death bolt going off when target not in room

### ISSUE THREAD

**Issue by druzuul** [Mud-xyz/evermore-bugs#5]
**Describe the bug**
if its started casting and the target flees the room it will still go off no matter how far the target has ran. It also makes it so you are engaged in autoattacks in different rooms. I couldnt use skills while auto attacking in different rooms. This also happened when someone started casting, and the target died. The spell still landed when the target respawned and they were engaged in combat again.

**To Reproduce**
1. Logged into forest map with character Vexx
2. Killed a goat
...

**Expected behavior**
Normally if the target leaves the room before the cast finishes it sputters or stops chanting. An option is allow it to finish even if the target is out of the room, but having it start engaging in autoattacks shouldnt happen.

**Screenshots or Output Logs**

**Additional context**

**Comment by ratacat** [comment]
This is currently expected, death bolt was changed to 'follow' targets. The incidence of it following them past death has been fixed.
