### ISSUE TITLE
500 on signing in

### ISSUE THREAD

**Issue by c0mput3rxz** [Mud-xyz/evermore-bugs#7]
**Describe the bug**
500 error signing in to characters at the time of match

**To Reproduce**
Pick a match 
1. Pick a character that has previously played a match.
2. Sign transaction to join the match
3. 500 error saying character already created
4. close error and play.

**Expected behavior**

**Screenshots or Output Logs**

**Additional context**
1. Likely due to character being stored in data from a previous match.
2. need to clear out data characters from repo
...

**Comment by gvanderest** [comment]
This was fixed.. I was accidentally looping the requests, so one attempt at joining was actually three.
